ARG NODE_VERSION=22.11.0
FROM node:${NODE_VERSION}-slim

WORKDIR /next

ENV NODE_ENV="development"
ENV NEXT_PUBLIC_API_BASE_URL="http://localhost:3000/api"

RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y build-essential node-gyp pkg-config python-is-python3

COPY package-lock.json package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production=false

COPY . .

EXPOSE 3001
CMD [ "npm", "run", "dev" ]
