ARG NODE_VERSION=22.11.0
FROM node:${NODE_VERSION}-slim

WORKDIR /next

RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y build-essential node-gyp pkg-config python-is-python3

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production=false

COPY .env.local ./
COPY . .

EXPOSE 3002
CMD [ "yarn", "dev" ]
