ARG NODE_VERSION=22.11.0
FROM node:${NODE_VERSION}-slim

WORKDIR /app

# hadolint ignore=DL3008
RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y build-essential node-gyp pkg-config python-is-python3 && \
  rm -rf /var/lib/apt/lists /var/cache/apt/archives

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production=false && \
  yarn cache clean

COPY .env.local ./
COPY . .

EXPOSE 3002
CMD [ "yarn", "dev" ]
