ARG RUBY_VERSION=3.3.5
FROM ruby:$RUBY_VERSION-slim

WORKDIR /app

RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y build-essential git libpq-dev libvips pkg-config

ENV RAILS_ENV="development"

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

EXPOSE 3000
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
